//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDMDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MDMGoldenRecord
    {
        public string BusinessKey { get; set; }
        public Nullable<int> provid { get; set; }
        public Nullable<int> EchoDrid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string ProviderFullName { get; set; }
        public string Provtype { get; set; }
        public string ProviderTypeDesc { get; set; }
        public Nullable<int> Claimtype { get; set; }
        public Nullable<int> Obs_claimtype { get; set; }
        public Nullable<int> LicenseNumber { get; set; }
        public Nullable<int> DOB { get; set; }
        public Nullable<int> SSN { get; set; }
        public string NPI { get; set; }
        public Nullable<int> EmploymentCode { get; set; }
        public Nullable<int> EmploymentDescription { get; set; }
        public Nullable<int> Specialtycode { get; set; }
        public Nullable<int> SpecialtyDescription { get; set; }
        public Nullable<int> Profdesig { get; set; }
        public Nullable<int> PracAddressType { get; set; }
        public Nullable<int> PracAddressTypeDesc { get; set; }
        public string Addr { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> EffDate { get; set; }
        public Nullable<int> TermDate { get; set; }
        public Nullable<int> BillAddressType { get; set; }
        public Nullable<int> BillAddressTypeDesc { get; set; }
        public string BillAddr { get; set; }
        public string Billaddr2 { get; set; }
        public string BillCity { get; set; }
        public string Billstate { get; set; }
        public string Billzip { get; set; }
        public string Billphone { get; set; }
        public string Billfax { get; set; }
        public Nullable<int> BillEffdate { get; set; }
        public Nullable<int> BillTermdate { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<int> QNXTID { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> echoid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> EchoIPAStatusCode { get; set; }
        public Nullable<int> EchoIPAStatusDescr { get; set; }
        public Nullable<int> EchoHospStatusCode { get; set; }
        public Nullable<int> EchoHOSPStatusDescr { get; set; }
        public Nullable<int> Echo_ACO_Active { get; set; }
        public Nullable<int> EchoIPAStatus { get; set; }
        public Nullable<int> EchoHOSPStatus { get; set; }
        public Nullable<int> Level1 { get; set; }
        public Nullable<int> Level2 { get; set; }
        public Nullable<int> Level3 { get; set; }
        public Nullable<int> Email { get; set; }
        public string TaxonomyCode { get; set; }
        public Nullable<int> spectype { get; set; }
        public string OrgName { get; set; }
    }
}
